### ISSUE TITLE
Auto Incrementation

### ISSUE THREAD

**Issue by cfehunter** [InvertedLlama/PPSD#4]
I've been re-writing the database handling code and I've ran into an issue with auto increment columns. Namely that adding a row via the datasource requires a valid value for every single field and doing so with an ID set in the program would lead to it becoming out of sync with the database or worse running into issues with constraints

For now i'm sticking with matt's code that commits to the database each time a record is added, in this way we can avoid it but we really shouldn't be doing it this way.
We should only commit when the user clicks save.

**Comment by InvertedLlama** [comment]
Couldn't you bypass this issue by using a sequence running on the DB server so that the program just points the auto ID column to the sequence and that value is added in the commit by the server.

ie from DB Systems:
INSERT INTO STAFF VALUES (SEQ_STAFF.NEXTVAL, (SELECT BRANCHID FROM BRANCHES WHERE TOWN='STAFFORD'), 'DAVID WALKER', 'MANAGING DIRECTOR', TO_DATE('20-FEB-2001', 'DD-MON-YYYY'),NULL,NULL);

**Comment by cfehunter** [comment]
No see the way the database interface works is this.

Pull data from a databse into a DataSet object or one of its sub classes (we're using DataTable mostly)

Add data to the dataTable

Call the Update method on the DataAdapterClass (sqlAdapter.Update(DataTable)).
This updates the database to be inline with the table. So if we were to set the table to require an ID what we'd end up with is something like this happening.

Database:
id  | text
0 | a
1 | b
2 | c

Both client A and client B pull this data
Client A adds data so their table looks like this:
id  | text
0 | a
1 | b
2 | c
3 | d

client B also Adds Data at the same time so their table looks like this
id  | text
0 | a
1 | b
2 | c
3 | E

Client A commts to the database:
The database now looks like this
id  | text
0 | a
1 | b
2 | c
3 | d

Cleint B tries to commit:
Database throws an error because a row with an ID of three already exists. Client crashes and the system dies.

Edit:
Also it seems MySQL doesn't support sequences. Just autoincrementing columns.
